Mitchell images database
kelseyp/munch pull request #50
Opened 2023-03-27 19:07 UTC by bluesheepllama

added images
added the blob image type to the back end

2023-04-13 03:09 UTC, kelseyp requested changes
Please review comments and complete changes before approval.

2023-04-13 03:09 UTC, kelseyp commented on backend/src/entity/FoodItem.ts
> +import { Blob } from "buffer"
It doesn't look like the Blob import is being used. If not, this should be removed

2023-04-13 03:09 UTC, kelseyp commented on backend/src/migration/initialize-database.ts
> +import { Blob } from "buffer";
Please remove unused imports.

2023-04-13 03:09 UTC, kelseyp commented on backend/src/index.ts
> -    origin: 'http://127.0.0.1:3000',
This was a local fix for your machine. Please revert to leave leave as-is in dev.

2023-04-15 03:09 UTC, kelseyp approved these changes

2023-04-17 02:34 UTC, xulean commented on backend/src/migration/initialize-database.ts
> +        foodItem.image = "../../../shared/data/images/" + rawItem.Image;
it is a hard code, you can store the entire path in the record in furture.

2023-04-17 02:36 UTC, xulean approved these changes

2023-04-17 02:43 UTC, merged