dietary info
kelseyp/munch pull request #88
Opened 2023-05-03 20:54 UTC by bluesheepllama

added all the dietary info

2023-05-04 02:56 UTC, kelseyp requested changes
I've added a number of suggestions for correcting typos. Additionally, is it correct to remove most double quotes around descriptions and image names? How has this been tested?

2023-05-04 02:56 UTC, kelseyp commented on shared/data/DatabaseItems.csv
> +Lighthouse Cafe,Fries,2.59,choice of sauce Vegetarian. Vegan. Dairy Free.,fries.jpg
```suggestion
Lighthouse Cafe,Fries,2.59,choice of sauce. Vegetarian. Vegan. Dairy Free.,fries.jpg
```

2023-05-04 02:56 UTC, kelseyp commented on shared/data/DatabaseItems.csv
> +Lighthouse Cafe,Veggie Wrap,5.59,"Spring mix. shredded carrots, tomatoes, cucumber, avacado, balsamic dressing in a flour tortilla. Vegetarian.. Vegan. Dairy Free.",veggie_wrap.jpg
```suggestion
Lighthouse Cafe,Veggie Wrap,5.59,"Spring mix. shredded carrots, tomatoes, cucumber, avacado, balsamic dressing in a flour tortilla. Vegetarian. Vegan. Dairy Free.",veggie_wrap.jpg
```

2023-05-04 02:56 UTC, kelseyp commented on shared/data/DatabaseItems.csv
> +Mom Wong Kitchen,Fried Cruller,1.49,Deep-fried pastry. Vegetarian. ,Fried_Cruller.jpg
```suggestion
Mom Wong Kitchen,Fried Cruller,1.49,Deep-fried pastry. Vegetarian.,Fried_Cruller.jpg
```

2023-05-04 02:56 UTC, kelseyp commented on shared/data/DatabaseItems.csv
> +Mom Wong Kitchen,Shrimp and Chive Egg Dumpling,10.49,"Dumpling filled with shrimp and chive egg, can be boiled, fried, or steamed. Dairy Free",Shrimp_and_Chive_Egg_Dumpling.jpg
```suggestion
Mom Wong Kitchen,Shrimp and Chive Egg Dumpling,10.49,"Dumpling filled with shrimp and chive egg, can be boiled, fried, or steamed. Dairy Free.",Shrimp_and_Chive_Egg_Dumpling.jpg
```

2023-05-04 02:56 UTC, kelseyp commented on shared/data/DatabaseItems.csv
> +Mom Wong Kitchen,Shrimp Hand-Ripped Noodle with Special Sauce,11.49,"Noodles made by hand-pulling wheat flour dough, served with shrimp and special sauce Dairy Free.",Shrimp_Hand-Ripped_Noodle_with_S
```suggestion
Mom Wong Kitchen,Shrimp Hand-Ripped Noodle with Special Sauce,11.49,"Noodles made by hand-pulling wheat flour dough, served with shrimp and special sauce. Dairy Free.",Shrimp_Hand-Ripped_Noodle_with_Special_Sauce.jpg
```

2023-05-04 02:56 UTC, kelseyp commented on shared/data/DatabaseItems.csv
> +Mom Wong Kitchen,Stir-Fried Baby Bok Choy,10.49,Stir-Fried Baby Bok Choy served with rice. Vegetarian.. Vegan. Dairy Free. Low Carb.,Stir-Fried_Baby_Bok_Choy.jpg
```suggestion
Mom Wong Kitchen,Stir-Fried Baby Bok Choy,10.49,Stir-Fried Baby Bok Choy served with rice. Vegetarian. Vegan. Dairy Free. Low Carb.,Stir-Fried_Baby_Bok_Choy.jpg
```

2023-05-05 03:05 UTC, kelseyp commented on shared/data/DatabaseItems.csv
> +Pizza 3.14,Garlic Bread,3,"Bread with Garlic and Butter. Vegetarian.","garlic_bread.jpg"
Did you mean to remove the 0's from the end of these prices?

2023-05-07 04:29 UTC, kelseyp approved these changes

2023-05-07 05:42 UTC, NathanaelPaulus approved these changes
Good job! Can't wait to see it all come together

2023-05-07 06:00 UTC, merged