Munch task87
kelseyp/munch pull request #90
Opened 2023-05-13 02:40 UTC by xulean

added 126 images

2023-05-14 02:54 UTC, xulean commented
please review it

2023-05-14 03:16 UTC, kelseyp requested changes, later dismissed

2023-05-14 03:16 UTC, kelseyp commented on backend/.gitignore
Please do not delete the .gitignore

2023-05-14 03:16 UTC, kelseyp commented on frontend/.gitignore
Please do not delete the .gitignore

2023-05-14 03:16 UTC, kelseyp commented on backend/package-lock.json
There should be no reason to delete the package-lock.json

2023-05-14 03:16 UTC, kelseyp commented on frontend/package-lock.json
There should be no reason to delete the package-lock.json

2023-05-15 03:24 UTC, austinhedrick548 approved these changes
Works good, just doesn't load in codespaces for some reason

2023-05-15 03:39 UTC, NathanaelPaulus approved these changes
looks good

2023-05-15 03:40 UTC, merged